function h_sym = Fn_SLPIAHDR_out(in1,in2,TrRate)
%Fn_SLPIAHDR_out
%    H_SYM = Fn_SLPIAHDR_out(IN1,IN2,TrRate)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-May-2023 16:25:34

A = in1(5,:);
H = in1(6,:);
I = in1(4,:);
L = in1(2,:);
P = in1(3,:);
S = in1(1,:);
delta = in2(6,:);
gamma = in2(7,:);
rhoA = in2(3,:);
rhoI = in2(4,:);
zeta = in2(2,:);
t2 = A.*delta;
t3 = gamma-1.0;
t4 = 1.0./rhoA;
t5 = 1.0./rhoI;
t6 = 1.0./zeta;
t7 = gamma.*t5;
t8 = I+P+t2;
t9 = delta.*t3.*t4;
t10 = -t9;
t11 = t6+t7+t10;
h_sym = [A+H+I+L+P;(S.*TrRate.*t8)./9.967304e+6;TrRate.*t11;(S.*TrRate.*t11)./9.967304e+6;t8];
